

services:
  # ----------------------------------------
  # Apache ActiveMQ Artemis
  # ----------------------------------------
  activemq:
    image: apache/activemq-artemis:latest
    container_name: activemq-artemis
    restart: unless-stopped
    ports:
      - "8161:8161"    # Web Console
      - "61616:61616"  # JMS (Core/OpenWire)
      - "5672:5672"    # AMQP
      - "1883:1883"    # MQTT
      - "61613:61613"  # STOMP
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    networks:
      app-net:
        aliases: [ activemq , artemis ]

  # ----------------------------------------
  # Apache Kafka 
  # ----------------------------------------
  kafka:
    image: apache/kafka:4.0.1
    container_name: kafka
    restart: unless-stopped
    ports:
    - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      app-net:
        aliases: [ kafka , broker ]

  # ----------------------------------------
  # Redis
  # ----------------------------------------
  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      app-net:
        aliases: [ redis ]
        
networks:
  app-net:
    name: messaging-net
    driver: bridge